### ISSUE TITLE
Unusual error when running pipeline

### ISSUE THREAD

**Issue by Al-Murphy** [yakirr/sldp#12]
Hey,

I have a weird error occurring when running SDLP on my own annotations and summary statistics. See below for the last few output lines of code and the error message:

```
10025 sumstats nans out of 17040
reading annotations
64.2657580376 : reading annot ./data/sldp/maf5/
adding ['minor1.R', 'minor2.R', 'minor3.R', 'minor4.R', 'minor5.R']
64.3660371304 : reading annot ./data/qtl/NEU_PU1_maxBeta_for_processed_PGCALZ2sumstatsExcluding23andMe_annots/
adding ['Eff_NEU_PU1_maxBeta.R']
65.2195940018 : loading chr 22 of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
17489 snps in refpanel 6 columns, including metadata
reading sumstats
10408 sumstats nans out of 17489
reading annotations
65.311809063 : reading annot ./data/sldp/maf5/
adding ['minor1.R', 'minor2.R', 'minor3.R', 'minor4.R', 'minor5.R']
65.4121751785 : reading annot ./data/qtl/NEU_PU1_maxBeta_for_processed_PGCALZ2sumstatsExcluding23andMe_annots/
adding ['Eff_NEU_PU1_maxBeta.R']
jackknifing
0 Eff_NEU_PU1_maxBeta.R
Traceback (most recent call last):
  File "/home/aemurphy/anaconda3/envs/sldp/bin/sldp", line 382, in <module>
    main(args)
  File "/home/aemurphy/anaconda3/envs/sldp/bin/sldp", line 166, in main
    q, r, mux, muy = cs.residualize(chunk_nums, chunk_denoms, len(background_names), k)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/sldp/chunkstats.py", line 96, in residualize
    muy = np.linalg.solve(ATA, ATy)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 403, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

Have you ever come across this before? I could share the data to reproduce this error but it is quite large so I wanted to check for a quick solution first. To note, I have used the same annotation files with a different GWAS sumstats and I don't get the error so I assume the problem is my summary statistics file but I can't see any problems with it? Here is a preview of it:

```
                 SNP CHR       BP A1 A2           Z           P      N
      1:  rs12238997   1   693731  A  G -1.04956969 0.293915998 145339
      2: rs189800799   1   701835  T  C  1.58177913 0.113700000  74004
      3:  rs72631875   1   705882  G  A  0.02075176 0.983443683 145339
      4: rs114983708   1   714019  A  G  1.81855073 0.068980000  74004
      5:  rs12184267   1   715265  C  T  2.89696241 0.003767949 441269
     ---                                                              
2491016:   rs6010080  22 51199058  T  C -0.50483183 0.613676959 137930
2491017:   rs9616974  22 51217954  G  A  0.86833986 0.385208307 517354
2491018:  rs28729663  22 51219006  G  A  0.13383285 0.893534748 506712
2491019: rs115055839  22 51221731  T  C  0.91569918 0.359824693 517167
2491020:   rs9616985  22 51229805  T  C  1.13342247 0.257036880 516378
```

The code fails on line 166 of `sldp.py` with the call:

```
q, r, mux, muy = cs.residualize(chunk_nums, chunk_denoms, len(background_names), k)
```

It's hard for me to debug it as I'm not clear how the `chunk_nums` and `chunk_denoms` files are created.

To note I also process my input files so only the overlapping SNPs between the annotations and the GWAS are passed to SLDP and I pass the annotation folder with the annotations split by chromosome. The command I run is:

```
sldp --sumstats-stem ./data/gwas/processed_PGCALZ2sumstatsExcluding23andMe_for_NEU_PU1_maxBeta --sannot-chr ./data/qtl/NEU_PU1_maxBeta_for_processed_PGCALZ2sumstatsExcluding23andMe_annots/ --outfile-stem ./results/predictions_sldp/processed_PGCALZ2sumstatsExcluding23andMe_NEU_PU1_maxBeta --config ./metadata/sldp_config.json
```

I use the same config file as the one given in your example and I'm SLDP v1.1.3 and Python v2.7.

**Comment by yakirr** [comment]
Hi Alan,

Usually this error happens when there is some co-linearity between the annotations or between the annotations and the background model. Might the annotation you're trying to run turn out to be a linear combination of the annotations in the background model?

Let me know,
Yakir

**Comment by Al-Murphy** [comment]
Hey Yakir,

Do you know of a way I could test this, maybe using some intermediary files from the SDLP run? I'm not sure how there could be colinearities, given the background model is split into 5 parts based on the MAF. I'm using a GWAS sumstats and QTL set as my annotations and have not filtered either on MAF or p-value etc.

Cheers,
Alan.

**Comment by yakirr** [comment]
Hi Alan, is this issue still ongoing? Apologies for my delay!

The residualization that is having trouble is run separately on each LD block. Given that you were able to run this annotation successfully with other sumstats, I wonder if the summary statistics file you're using might have very few typed SNPs in some LD block and this in turn allows for colinearities to emerge among annotations in the background model. Might it be worth checking how many typed SNPs are in each LD block for your summary statistics?
