### ISSUE TITLE
TypeError issue when running demo

### ISSUE THREAD

**Issue by danieljrichard** [yakirr/sldp#6]
Hello,
I'd been attempting to run SLDP after installing all the initial files, along with installing sldp with 'pip install sldp', however, when running the command provided by the wiki:
"
sldp --pss-chr CD.KG3.95/ \
    --sannot-chr SydhK562Irf1Ifng6h/ \
    --background-sannot-chr maf5/ \
    --outfile-stem CD.Irf1 \
    --ld-blocks pickrell_ldblocks.hg19.eur.bed \
    --svd-stem svds_95percent/ \
    --bfile-reg-chr plink_files/1000G.EUR.QC.hm3_noMHC. \
    --seed 0
"

It runs for a little while, but then appears to get stuck at the 'jackknifing' stage:
 
Traceback (most recent call last):
  File "/home/daniel/anaconda3/bin/sldp", line 382, in <module>
    main(args)
  File "/home/daniel/anaconda3/bin/sldp", line 159, in main
    mu = cs.get_est(sum(chunk_nums), sum(chunk_denoms), k, len(background_names))
  File "/home/daniel/anaconda3/lib/python3.9/site-packages/sldp/chunkstats.py", line 58, in get_est
    ind = range(num_background) + [num_background+k]
TypeError: unsupported operand type(s) for +: 'range' and 'list'

Am I perhaps using the wrong version of python?
Any assistance would be greatly appreciated.

**Comment by danieljrichard** [comment]
Nevermind - it was a simple as adding a list(range(num_background)) to that line in chunkstats, and things appear to be running again.
