### ISSUE TITLE
Running sldp on all 381 TF annotations at once

### ISSUE THREAD

**Issue by WeiCSong** [yakirr/sldp#9]
HI, I noticed that the downloaded basset.tar stroed annotations of each TF as separate file, thus the sldp must run against them in a for loop. In LDSC, multiple annotations could be stored in one .annot file, and can be analyzed by one command. Is this capable for sldp? Thanks for your help.

**Comment by WeiCSong** [comment]
Another little bug when i tried to run sldp on single annotation:

> =====
/dssg/home/acct-bmelgn/bmelgn-3/deepsea/deepsea/sldp/sldp/sldp --sumstats-stem /dssg/home/acct-bmelgn/bmelgn-3/ldsc/sumstat/ACR.AD --sannot-chr seqannot/ago_adult_brain.BA4.hg19 --outfile-stem sldpres/ago_adult_brain.BA4.hg19.ACR.AD --config /dssg/home/acct-bmelgn/bmelgn-3/ldsc/config.txt
=====
T                        1000000
background_sannot_chr    ['/dssg/home/acct-bmelgn/bmelgn-3/ldsc/maf5/']
bfile_chr                /dssg/home/acct-bmelgn/bmelgn-3/ldsc/EUR/EUR/1000G.EUR.QC.
bfile_reg_chr            /dssg/home/acct-bmelgn/bmelgn-3/ldsc/plink_files/1000G.EUR.QC.hm3_noMHC.
bothp                    False
chi2_thresh              0
chroms                   range(1, 23)
config                   /dssg/home/acct-bmelgn/bmelgn-3/ldsc/config.txt
fastp                    False
jk_blocks                300
ld_blocks                /dssg/home/acct-bmelgn/bmelgn-3/ldsc/pickrell_ldblocks.hg19.eur.bed
ldscores_chr             /dssg/home/acct-bmelgn/bmelgn-3/ldsc/LDscore/LDscore.
more_stats               False
outfile_stem             sldpres/ago_adult_brain.BA4.hg19.ACR.AD
print_snps               /dssg/home/acct-bmelgn/bmelgn-3/ldsc/1000G_hm3_noMHC.rsid
pss_chr                  None
refpanel_name            KG3.95
sannot_chr               ['seqannot/ago_adult_brain.BA4.hg19']
seed                     None
stat                     sum
story_corr_thresh        0.8
sumstats_stem            /dssg/home/acct-bmelgn/bmelgn-3/ldsc/sumstat/ACR.AD
svd_stem                 /dssg/home/acct-bmelgn/bmelgn-3/ldsc/svds_95percent/
tell_me_stories          0.0
verbose_thresh           0.0
weights                  Winv_ahat_h
=====
Preprocessing /dssg/home/acct-bmelgn/bmelgn-3/ldsc/sumstat/ACR.AD.sumstats.gz... at [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Using config file /dssg/home/acct-bmelgn/bmelgn-3/ldsc/config.txt and default options
initializing...
1187349 svd snps
reading sumstats /dssg/home/acct-bmelgn/bmelgn-3/ldsc/sumstat/ACR.AD
1158348 snps, 14987.0-16696.0 individuals (avg: 16559.62172853063)
1146680 snps typed
reading in ld scores
Traceback (most recent call last):
  File "/dssg/home/acct-bmelgn/bmelgn-3/deepsea/deepsea/sldp/sldp/sldp", line 379, in <module>
    preprocess_sumstats(args)
  File "/dssg/home/acct-bmelgn/bmelgn-3/deepsea/deepsea/sldp/sldp/sldp", line 255, in preprocess_sumstats
    sldp.preprocesspheno.main(args_)
  File "/dssg/home/acct-bmelgn/bmelgn-3/.conda/envs/r/lib/python3.10/site-packages/sldp/preprocesspheno.py", line 40, in main
    M = sum([int(open(args.ldscores_chr+str(c)+'.l2.M_5_50').next())
  File "/dssg/home/acct-bmelgn/bmelgn-3/.conda/envs/r/lib/python3.10/site-packages/sldp/preprocesspheno.py", line 40, in <listcomp>
    M = sum([int(open(args.ldscores_chr+str(c)+'.l2.M_5_50').next())
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'

Could you have a look at that? Thank you very much.

**Comment by yakirr** [comment]
Dear Song,

For your first question: try listing the annotation files one after the
other in the sldp command.
For your second question: what version of python are you using?

Yakir

**Comment by WeiCSong** [comment]
Dear Yakir,
Thanks for your reply! I'm using python 3.10.5 and sldp 1.1.3 installed from pip.

Weichen Song

**Comment by yakirr** [comment]
Weichen,

I apologize for the delay. I suspect that this is caused by your python
version. Could you try creating a virtual environment with python 3.7 and
seeing if you get the same error?
If this is a python version issue it is fixable, but it may take some time
to push the changes.

Keep me posted,
Yakir

**Comment by WeiCSong** [comment]
Hi, thanks for the suggestion! In enviroment with python 3.7, I found the following error:

> Traceback (most recent call last):
  File "/dssg/home/acct-bmelgn/bmelgn-3/.conda/envs/sldp/bin/sldp", line 382, in <module>
    main(args)
  File "/dssg/home/acct-bmelgn/bmelgn-3/.conda/envs/sldp/bin/sldp", line 33, in main
    marginal_infos = pd.concat([a.info_df(args.chroms) for a in annots], axis=0)
  File "/dssg/home/acct-bmelgn/bmelgn-3/.conda/envs/sldp/bin/sldp", line 33, in <listcomp>
    marginal_infos = pd.concat([a.info_df(args.chroms) for a in annots], axis=0)
  File "/dssg/home/acct-bmelgn/bmelgn-3/.conda/envs/sldp/lib/python3.7/site-packages/gprim/annotation.py", line 165, in info_df
    return reduce(lambda x,y:x+y,
NameError: name 'reduce' is not defined

I have also tried python 2.7 but the pip installation step failed due to version conflict. 

Best,
Weichen Song

**Comment by yakirr** [comment]
Hi Weichen, this does seem like a versioning issue. I thought we'd be able to get away with python 3.7 but it looks like that isn't the case. What error do you get when you try to install it with python 2.7?

**Comment by LeoJiny** [comment]
Hi Yakirr,
Same issue here! I also bump into the error "name 'reduce' is not defined when trying to run the minimal example of sldp. I'm using python = 3.10. I then created a new environment with python=3.7 and ran "pip install sldp". However, the installation doesn't work and I got this.
![Screenshot 2024-11-24 at 11 11 03 PM](https://github.com/user-attachments/assets/7631629f-3ab6-4c06-b4d7-b9046d00cc54)

![Screenshot 2024-11-24 at 11 09 19 PM](https://github.com/user-attachments/assets/f3e193c8-b7f1-419f-a56f-05a0d00dfb84)
